sudo: false

language: node_js

node_js:
  - "7"
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - make travis
